AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Babashka Lambda runtime packaged as a Lambda layer.
Resources:
  BabashkaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: babashka-runtime
      Description: Babashka runtime
      ContentUri: s3://pointer2-labs/babashka/faf03056b7a2094d14c189b46aea9af2
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/pavel-popov/babashka-lambda-layer/blob/master/LICENSE
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref BabashkaLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: babashka-runtime-lambda-layer
    Description: >
      Babashka lambda runtime packaged as a Lambda layer.
      Bundles Babashka 0.2.2.
    Author: Pavel Popov
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['layer', 'babashka', 'lambda', 'clojure']
    HomePageUrl: https://github.com/pavel-popov/babashka-lambda-layer
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/pavel-popov/babashka-lambda-layer
